name: CI

on: [pull_request]

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Building the project
      run: npm run build
    - name: Unit tests
      run: npm run test:unit --if-present
    - name: Integration Tests
      run: npm run test:integration --if-present
